<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-MG03N7G" failures="1" tests="8" name="com.lotustms.testcase.locationManagement_testCase" time="182.809" errors="0" timestamp="2022-09-12T15:00:00 IST" skipped="0">
  <testcase classname="com.lotustms.testcase.locationManagement_testCase" name="Tc_Customer_009" time="23.500"/>
  <system-out/>
  <testcase classname="com.lotustms.testcase.locationManagement_testCase" name="Tc_Customer_009" time="23.018">
    <failure message="expected [Chassis Depots] but found [abc]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Chassis Depots] but found [abc]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.lotustms.testcase.locationManagement_testCase.Tc_Customer_009(locationManagement_testCase.java:255)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Tc_Customer_009 -->
  <system-out/>
  <testcase classname="com.lotustms.testcase.locationManagement_testCase" name="Tc_Customer_009" time="21.449"/>
  <system-out/>
  <testcase classname="com.lotustms.testcase.locationManagement_testCase" name="Tc_Customer_009" time="21.580"/>
  <system-out/>
  <testcase classname="com.lotustms.testcase.locationManagement_testCase" name="Tc_Customer_009" time="28.166"/>
  <system-out/>
  <testcase classname="com.lotustms.testcase.locationManagement_testCase" name="Tc_Customer_009" time="21.033"/>
  <system-out/>
  <testcase classname="com.lotustms.testcase.locationManagement_testCase" name="Tc_Customer_009" time="21.651"/>
  <system-out/>
  <testcase classname="com.lotustms.testcase.locationManagement_testCase" name="Tc_Customer_009" time="22.412"/>
  <system-out/>
</testsuite> <!-- com.lotustms.testcase.locationManagement_testCase -->
